#include "main.h"
#include "PWM_Set.h"
#include "GPIO_Set.h"

#define  AIN1 GPIO_PIN_1
#define  AIN2 GPIO_PIN_2
#define  PWM_Pin GPIO_PIN_3
#define  STBY GPIO_PIN_4
#define  GPIO_Port GPIOA

void TB6612FNG_Init(void) {
	__HAL_RCC_GPIOA_CLK_ENABLE();
	GPIO_CFG(GPIO_Port, AIN1 | AIN2 | STBY, GPIO_MODE_OUTPUT_PP, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_NOPULL);
	GPIO_AF_CFG(GPIO_Port, PWM_Pin, GPIO_MODE_AF_PP, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_NOPULL, GPIO_AF1_TIM2);
	__HAL_RCC_TIM2_CLK_ENABLE();
	TIM_Base_CFG(TIM2, 84 - 1, 1000 - 1, TIM_CLOCKDIVISION_DIV1, TIM_COUNTERMODE_UP);
	TIM_PWM_CFG(TIM2, TIM_OCMODE_PWM1, 0, TIM_OCPOLARITY_HIGH, TIM_CHANNEL_4);
	HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_4);
}

void TB6612FNG_SetSpeed(uint16_t speed) {
	if(speed >= 1000) speed = 999;
	__HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_4, speed);
}
